### ISSUE TITLE
practices.md doesn't display new column

### ISSUE THREAD

**Issue by NicoloSantorio** [academie-de-espee/earl-marshal#28]
I've been updating the data in practices.csv to have a new column for date last updated.  I also updated practices.md to make a new place for the column.  However, for some reason the new column "Last Updated" doesn't appear on the site even after the merge.  Can you help troubleshoot?

Page in question:  
https://marshal.atlantia.sca.org/practices/rapier/

**Comment by chsnell** [comment]
https://github.com/academie-de-espee/earl-marshal/blob/master/practices/rapier.md?plain=1 doesn't seem to show the new column in the raw code of the file.  Did it get missed getting submitted in your PRs, maybe?

**Comment by NicoloSantorio** [comment]
Oh I see, rapier.md, not practices.md

New pull submitted.

**Comment by demoray** [comment]
The new PR includes the column, but not the column header.  Can that be added?

**Comment by NicoloSantorio** [comment]
Missed that.  Added a column header to a new pull.
